root: true
extends:
  - 'eslint:recommended'
  - prettier
plugins:
  - simple-import-sort
  - import
rules:
  import/first: error
  import/newline-after-import: error
  import/no-duplicates: error
  simple-import-sort/exports: error
overrides:
  - files: [.eslintrc.cjs, '*.config.*', package-scripts.cjs]
    env:
      node: true
      es6: true
  - files: '*.{ts,tsx}'
    extends:
      - 'plugin:@typescript-eslint/strict-type-checked'
      - 'plugin:@typescript-eslint/stylistic-type-checked'
    plugins:
      - '@typescript-eslint'
    parser: '@typescript-eslint/parser'
    parserOptions:
      project: true
    rules:
      '@typescript-eslint/no-namespace': 'off'
